// Reads the trial/alert data for the app.
//
// The data comes from a JSON snapshot (src/data/snapshot.json) generated by the
// scraper (`npm run scrape` / `npm run snapshot`). Importing the JSON means the
// data is bundled at build time — no database or native module at runtime — so
// the app runs identically locally and on serverless hosts like Vercel.
//
// To update the deployed data: re-scrape locally, commit the new snapshot, redeploy.

import type {
  Alert,
  AlertSeverity,
  AlertType,
  Comm,
  Trial,
  TrialPhase,
  TrialStatus,
} from "./types";
import {
  alertsForWorkspace as mockAlertsForWorkspace,
  trialsForWorkspace as mockTrialsForWorkspace,
} from "./mockData";
import snapshotJson from "@/data/snapshot.json";

// The snapshot workspace — data is currently ovarian-only.
const SNAPSHOT_WORKSPACES = new Set(["ws_ovarian"]);

interface TrialRow {
  nct_id: string;
  title: string | null;
  sponsor: string | null;
  sponsor_class: string | null;
  study_type: string | null;
  phase: string | null;
  status: string | null;
  enrollment: number | null;
  primary_completion_date: string | null;
  interventions: string | null;
  conditions: string | null;
  countries: string | null;
  last_updated: string | null;
  dropped_at: string | null;
}

interface AlertRow {
  id: number;
  workspace_id: string;
  nct_id: string;
  sponsor: string | null;
  type: string;
  severity: string;
  title: string;
  summary: string | null;
  field: string | null;
  old_value: string | null;
  new_value: string | null;
  created_at: string;
  read: number;
}

interface CommRow {
  nct_id: string;
  matched_term: string | null;
  source: string | null;
  cik: string | null;
  company: string | null;
  form: string | null;
  filed_date: string | null;
  item_codes: string | null;
  accession: string | null;
  doc_url: string | null;
  description: string | null;
  summary: string | null;
}

const snapshot = snapshotJson as {
  generatedAt: string;
  trials: TrialRow[];
  alerts: AlertRow[];
  comms?: CommRow[];
};

// CT.gov status codes -> human labels used in the UI.
const STATUS_LABELS: Record<string, TrialStatus> = {
  NOT_YET_RECRUITING: "Not yet recruiting",
  RECRUITING: "Recruiting",
  ENROLLING_BY_INVITATION: "Active, not recruiting",
  ACTIVE_NOT_RECRUITING: "Active, not recruiting",
  COMPLETED: "Completed",
  TERMINATED: "Terminated",
  SUSPENDED: "Suspended",
  WITHDRAWN: "Withdrawn",
};

function safeParse<T>(json: string | null, fallback: T): T {
  if (!json) return fallback;
  try {
    return JSON.parse(json) as T;
  } catch {
    return fallback;
  }
}

function mapTrial(row: TrialRow, workspaceId: string): Trial {
  const interventions = safeParse<string[]>(row.interventions, []);
  const conditions = safeParse<string[]>(row.conditions, []);
  return {
    nctId: row.nct_id,
    workspaceId,
    title: row.title ?? "",
    sponsor: row.sponsor ?? "Unknown",
    intervention: interventions.join(", ") || "—",
    // No clean mechanism/MoA field from CT.gov — populated later by classification.
    mechanism: "",
    indication: conditions[0] ?? "Ovarian cancer",
    phase: (row.phase ?? "N/A") as TrialPhase,
    status:
      STATUS_LABELS[row.status ?? ""] ??
      ((row.status ?? "Unknown") as TrialStatus),
    enrollmentCount: row.enrollment ?? 0,
    primaryCompletionDate: row.primary_completion_date ?? undefined,
    lastUpdated: row.last_updated ?? "",
    droppedAt: row.dropped_at ?? undefined,
  };
}

function mapAlert(row: AlertRow): Alert {
  return {
    id: String(row.id),
    workspaceId: row.workspace_id,
    type: row.type as AlertType,
    severity: (row.severity as AlertSeverity) ?? "info",
    title: row.title,
    summary: row.summary ?? "",
    nctId: row.nct_id,
    sponsor: row.sponsor ?? "",
    change: row.field
      ? { field: row.field, from: row.old_value ?? "", to: row.new_value ?? "" }
      : undefined,
    createdAt: row.created_at,
    read: Boolean(row.read),
  };
}

function mapComm(row: CommRow): Comm {
  return {
    nctId: row.nct_id,
    matchedTerm: row.matched_term ?? "",
    source: row.source ?? "edgar",
    cik: row.cik ?? "",
    company: row.company ?? "Unknown filer",
    form: row.form ?? "",
    filedDate: row.filed_date ?? "",
    itemCodes: row.item_codes ?? "",
    accession: row.accession ?? "",
    docUrl: row.doc_url ?? "",
    description: row.description ?? "",
    summary: row.summary ?? "",
  };
}

/**
 * Company communications (EDGAR filings) for a single trial, newest first.
 */
export function getTrialComms(nctId: string): Comm[] {
  return (snapshot.comms ?? [])
    .filter((c) => c.nct_id === nctId)
    .map(mapComm)
    .sort((a, b) => (a.filedDate < b.filedDate ? 1 : -1));
}

/** Count of comms per trial, for badges/links in the trial table. */
export function getCommCounts(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const c of snapshot.comms ?? []) {
    counts[c.nct_id] = (counts[c.nct_id] ?? 0) + 1;
  }
  return counts;
}

/**
 * Trials for a workspace. Snapshot-backed for ovarian (falls back to mock if the
 * snapshot is empty); mock for everything else.
 */
export function getWorkspaceTrials(workspaceId: string): Trial[] {
  if (!SNAPSHOT_WORKSPACES.has(workspaceId) || snapshot.trials.length === 0) {
    return mockTrialsForWorkspace(workspaceId);
  }
  return snapshot.trials.map((r) => mapTrial(r, workspaceId));
}

/**
 * Alerts for a workspace, newest first. Snapshot-backed for ovarian; mock for
 * everything else.
 */
export function getWorkspaceAlerts(workspaceId: string): Alert[] {
  if (!SNAPSHOT_WORKSPACES.has(workspaceId)) {
    return mockAlertsForWorkspace(workspaceId);
  }
  return snapshot.alerts
    .filter((a) => a.workspace_id === workspaceId)
    .map(mapAlert);
}
