// Reads the T-cell engager (TCE) snapshot for the /engagers page.
//
// Data comes from src/data/tce-snapshot.json, generated by the TCE pipeline
// (`npm run tce` → `npm run tce:classify` → `npm run tce:snapshot`). Bundled at
// build time, so no DB/native module at runtime (same model as src/lib/db.ts).

import tceSnapshot from "@/data/tce-snapshot.json";

export interface TceTrial {
  nctId: string;
  title: string | null;
  summary: string;
  sponsor: string | null;
  sponsorClass: string | null;
  phase: string | null;
  status: string | null;
  enrollment: number | null;
  primaryCompletionDate: string | null;
  conditions: string[];
  interventions: string[];
  countries: string[];
  matchedTerms: string[];
  enrollsOvarian: boolean;
  hasUsSites: boolean;
  drug: string | null;
  isTce: boolean;
  tCellArm: string | null;
  tumorTarget: string | null;
  targetPair: string | null;
  modality: string | null;
  confidence: string | null;
  classificationSource: string | null;
  lastUpdated: string | null;
}

interface TceSnapshot {
  generatedAt: string;
  total: number;
  tceCount: number;
  muc16Count: number;
  trials: TceTrial[];
}

const snapshot = tceSnapshot as TceSnapshot;

export function getTceSnapshot(): TceSnapshot {
  return snapshot;
}

export function getTceTrials(): TceTrial[] {
  return snapshot.trials;
}
