// EDGAR ingestion — finds SEC filings ("company comms") mentioning each trial's
// drug(s) and links them to the trial by NCT id.
//
// Why drug-name matching (not sponsor): drugs move between companies via M&A and
// licensing (e.g. mirvetuximab filings are under ImmunoGen, but CT.gov lists the
// sponsor as AbbVie, which acquired them). We match on the distinctive drug name
// across ALL filers and attribute each comm to whoever actually filed it.
//
// Usage:
//   node scripts/edgar.mjs                 # all tracked trials
//   node scripts/edgar.mjs --limit 25      # cap filings fetched per drug
//   node scripts/edgar.mjs --since 2022-01-01
//   node scripts/edgar.mjs --dry-run       # query + report, don't write
//
// SEC etiquette: a descriptive User-Agent is required and requests are throttled.
// Override the UA with SEC_USER_AGENT="Your Co you@example.com".

import "./loadEnv.mjs"; // load .env.local before anything reads process.env
import Database from "better-sqlite3";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { ProxyAgent, setGlobalDispatcher } from "undici";
import Anthropic from "@anthropic-ai/sdk";
import { writeSnapshot } from "./snapshot.mjs";
import { drugTerms } from "./drugs.mjs";

const PROXY = process.env.https_proxy || process.env.HTTPS_PROXY;
if (PROXY) {
  // Both the CT.gov/EDGAR fetches and the Anthropic SDK (which uses global
  // fetch) route through this dispatcher.
  setGlobalDispatcher(new ProxyAgent(PROXY));
  console.log(`Using proxy: ${PROXY}`);
}

// AI summaries are generated by Claude when ANTHROPIC_API_KEY is set; otherwise
// we fall back to a heuristic lede extract so ingestion still works offline.
const SUMMARY_MODEL = process.env.CLARION_SUMMARY_MODEL || "claude-opus-4-8";
const anthropic = process.env.ANTHROPIC_API_KEY ? new Anthropic() : null;
let aiSummaryFailed = false; // set once if the API errors, to stop retrying

const __dirname = dirname(fileURLToPath(import.meta.url));
const DB_PATH = resolve(__dirname, "..", "data/clarion.db");

const EFTS = "https://efts.sec.gov/LATEST/search-index";
const FORMS = ["8-K", "6-K", "10-K", "10-Q", "20-F"]; // high-signal disclosures
const USER_AGENT = process.env.SEC_USER_AGENT || "Clarion CI research contact@example.com";

function parseArgs(argv) {
  const args = { limit: 10, pages: 3, since: "2021-01-01", dryRun: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--limit") args.limit = parseInt(argv[++i], 10) || args.limit;
    else if (a === "--pages") args.pages = parseInt(argv[++i], 10) || args.pages;
    else if (a === "--since") args.since = argv[++i];
    else if (a === "--dry-run") args.dryRun = true;
  }
  return args;
}

// ── company matching ─────────────────────────────────────────────────────────
// We only keep a filing if the FILER is (approximately) the trial's sponsor.
// Corporate suffixes and industry words are stripped so "AstraZeneca PLC" matches
// "AstraZeneca" and "Merck & Co., Inc." matches "Merck Sharp & Dohme LLC".
const COMPANY_STOPWORDS = new Set([
  "inc", "incorporated", "corp", "corporation", "co", "company", "ltd", "limited",
  "plc", "llc", "lp", "ag", "sa", "nv", "as", "oyj", "ab", "gmbh", "holdings",
  "holding", "pharmaceuticals", "pharmaceutical", "pharma", "therapeutics",
  "biosciences", "bioscience", "bio", "sciences", "science", "oncology", "group",
  "the", "and", "of", "laboratories", "labs", "health", "healthcare", "medicines",
  "medical", "biopharma", "biopharmaceuticals", "usa", "international",
]);

function companyTokens(name) {
  return new Set(
    String(name)
      .toLowerCase()
      .replace(/&/g, " ")
      .replace(/[^a-z0-9 ]/g, " ")
      .split(/\s+/)
      .filter((t) => t.length >= 3 && !COMPANY_STOPWORDS.has(t))
  );
}

function companyMatches(filer, sponsor) {
  if (!filer || !sponsor) return false;
  const a = companyTokens(filer);
  const b = companyTokens(sponsor);
  if (!a.size || !b.size) return false;
  for (const t of a) if (b.has(t)) return true; // shared significant token
  const na = [...a].join("");
  const nb = [...b].join("");
  return na.includes(nb) || nb.includes(na); // single-token brand containment
}

// ── summaries ────────────────────────────────────────────────────────────────
// No LLM is wired in, so we extract a clean lede from press-release exhibits
// (8-K / 6-K). Larger periodic reports (10-K/10-Q) are mostly boilerplate, so we
// skip summarizing those and let the UI fall back to the filing description.
const summaryCache = new Map();

function stripToText(html) {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&#?\w+;/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function leadExcerpt(text) {
  const t = text
    .replace(/^.*?exhibit\s*99\.\d+/i, "")
    .replace(/ex-99\.\d+\s*\d*\s*\S+\.htm\s*ex-99\.\d+/gi, "")
    .replace(/filed by[\s\S]{0,220}?(pursuant to rule[\s\S]{0,160}?193\d)/i, "")
    .replace(/commission file no\.?:?\s*\S+/gi, "")
    .replace(/subject company:[\s\S]{0,140}/i, "")
    .replace(/united states securities and exchange commission/gi, "")
    .replace(/\bform\s+\d+-?k\b/gi, "")
    .replace(/\s+/g, " ")
    .trim();
  const m = t.match(/^.{40,300}?[.!?](\s|$)/);
  return (m ? m[0] : t.slice(0, 280)).trim();
}

// Ask Claude for a tight, factual summary of what the filing says about the drug.
// Returns "" on any failure so the caller can fall back to the heuristic excerpt.
async function aiSummarize(text, { drug, company }) {
  if (!anthropic || aiSummaryFailed || !text) return "";
  try {
    const msg = await anthropic.messages.create({
      model: SUMMARY_MODEL,
      max_tokens: 320,
      system:
        "You summarize SEC filings for a pharma competitive-intelligence tool. " +
        "You are given excerpts from a filing surrounding each mention of a specific " +
        "drug. Write AT MOST 2 sentences (~60 words) on what the company says about " +
        "that drug — the most important clinical, regulatory, or competitive " +
        "development, with a few concrete specifics (phase, key result, date, " +
        "indication) when present. Lead with the headline development; if it would " +
        "run long, keep the single most important fact rather than listing " +
        "everything. No preamble, no marketing language. If the drug is only " +
        "mentioned in passing, reply exactly: \"Mentioned in passing.\"",
      messages: [
        {
          role: "user",
          content: `Drug: ${drug}\nFiler: ${company}\n\nExcerpts mentioning the drug:\n${text.slice(0, 8000)}`,
        },
      ],
    });
    const block = msg.content.find((b) => b.type === "text");
    return block ? block.text.trim() : "";
  } catch (err) {
    aiSummaryFailed = true; // don't hammer the API if creds/network are bad
    console.warn(`  ! AI summary failed (${err.message}); using excerpts for the rest.`);
    return "";
  }
}

// Pull the drug-relevant passage(s) out of a filing so we summarize what the
// company said about THIS drug — not the whole document. Finds the drug name
// (or a distinctive token of it) and returns windows of text around each mention,
// merged and capped. Returns "" if the drug isn't mentioned in the fetched doc.
function extractDrugPassages(text, drug, { window = 1500, maxChars = 8000 } = {}) {
  const hay = text.toLowerCase();
  // Prefer the full drug name; fall back to its most distinctive token
  // (e.g. "Mirvetuximab soravtansine" -> "mirvetuximab").
  const needles = [drug.toLowerCase()];
  for (const tok of drug.toLowerCase().split(/[^a-z0-9-]+/)) {
    if (tok.length >= 5 && !needles.includes(tok)) needles.push(tok);
  }
  const needle = needles.find((n) => hay.includes(n));
  if (!needle) return "";

  const ranges = [];
  for (let idx = hay.indexOf(needle); idx !== -1 && ranges.length < 25; ) {
    ranges.push([
      Math.max(0, idx - window),
      Math.min(text.length, idx + needle.length + window),
    ]);
    idx = hay.indexOf(needle, idx + needle.length);
  }
  // Merge overlapping windows.
  ranges.sort((a, b) => a[0] - b[0]);
  const merged = [];
  for (const r of ranges) {
    const last = merged[merged.length - 1];
    if (last && r[0] <= last[1]) last[1] = Math.max(last[1], r[1]);
    else merged.push(r);
  }
  let out = "";
  for (const [a, b] of merged) {
    if (out.length >= maxChars) break;
    out += (out ? "\n…\n" : "") + text.slice(a, b);
  }
  return out.slice(0, maxChars);
}

async function summarize(docUrl, form, drug, company) {
  if (!docUrl) return "";
  const cacheKey = `${docUrl}::${drug.toLowerCase()}`;
  if (summaryCache.has(cacheKey)) return summaryCache.get(cacheKey);
  let summary = "";
  try {
    const res = await fetch(docUrl, { headers: { "User-Agent": USER_AGENT } });
    if (res.ok) {
      let html = await res.text();
      // Large enough to reach the drug discussion deep inside a 10-K/10-Q.
      if (html.length > 2_000_000) html = html.slice(0, 2_000_000);
      const text = stripToText(html);
      const passage = extractDrugPassages(text, drug);
      // Only summarize the drug-relevant passage. If the drug isn't found in the
      // fetched document, leave the summary blank rather than describe the doc.
      if (passage) {
        summary = (await aiSummarize(passage, { drug, company })) || leadExcerpt(passage);
      }
    }
  } catch {
    // best-effort — leave summary empty on any fetch/parse failure
  }
  summaryCache.set(cacheKey, summary);
  await sleep(120);
  return summary;
}

// Pull distinctive drug names out of a trial's intervention list. Splits combos
// ("Niraparib + investigational agent") and drops generic/short terms.
// One request returns the top ~100 hits by relevance — the sponsor's own filings
// about their drug rank at the top, so that's enough after company-filtering.
// (Deep pagination on common drugs just re-fetches dupes and triggers 500s.)
async function searchFilings(term, args) {
  const params = new URLSearchParams({
    q: `"${term}"`,
    forms: FORMS.join(","),
    dateRange: "custom",
    startdt: args.since,
    enddt: "2099-12-31",
  });
  const url = `${EFTS}?${params.toString()}`;
  for (let attempt = 0; attempt < 2; attempt++) {
    const res = await fetch(url, {
      headers: { "User-Agent": USER_AGENT, Accept: "application/json" },
    });
    if (res.ok) {
      const data = await res.json();
      const hits = data.hits?.hits ?? [];
      const seen = new Set();
      const out = [];
      for (const h of hits) {
        if (seen.has(h._id)) continue;
        seen.add(h._id);
        out.push(mapHit(h));
      }
      return out;
    }
    if (res.status >= 500 && attempt === 0) {
      await sleep(600); // transient — retry once
      continue;
    }
    throw new Error(`EDGAR ${res.status} ${res.statusText} for "${term}"`);
  }
  return [];
}

function mapHit(hit) {
  const s = hit._source ?? {};
  const [accession, filename] = String(hit._id).split(":");
  const cikRaw = (s.ciks && s.ciks[0]) || "";
  const cik = parseInt(cikRaw, 10) || 0;
  const adshNoDash = String(accession).replace(/-/g, "");
  const docUrl = cik
    ? `https://www.sec.gov/Archives/edgar/data/${cik}/${adshNoDash}/${filename}`
    : "";
  const company = (s.display_names && s.display_names[0]) || "Unknown filer";
  return {
    accession,
    cik: String(cik),
    company: company.replace(/\s*\(CIK.*\)\s*$/, "").trim(),
    form: s.form || (s.root_forms && s.root_forms[0]) || "",
    filed_date: s.file_date || "",
    item_codes: Array.isArray(s.items) ? s.items.join(", ") : "",
    doc_url: docUrl,
    description: s.file_description || s.file_type || "",
  };
}

function openDb() {
  const db = new Database(DB_PATH, { fileMustExist: true });
  db.pragma("journal_mode = WAL");
  db.exec(`
    CREATE TABLE IF NOT EXISTS comms (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      nct_id TEXT,
      matched_term TEXT,
      source TEXT DEFAULT 'edgar',
      cik TEXT,
      company TEXT,
      form TEXT,
      filed_date TEXT,
      item_codes TEXT,
      accession TEXT,
      doc_url TEXT,
      description TEXT,
      summary TEXT,
      created_at TEXT,
      UNIQUE(nct_id, doc_url)
    );
  `);
  // Migrate older comms tables that predate the summary column.
  const cols = new Set(db.prepare(`PRAGMA table_info(comms)`).all().map((c) => c.name));
  if (!cols.has("summary")) db.exec(`ALTER TABLE comms ADD COLUMN summary TEXT`);
  return db;
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const db = openDb();

  // comms are fully re-derived from the current trial set each run, so clear the
  // EDGAR rows first (otherwise removed/retuned matches would linger).
  if (!args.dryRun) db.exec(`DELETE FROM comms WHERE source = 'edgar'`);

  const trials = db
    .prepare(`SELECT nct_id, sponsor, interventions FROM trials WHERE dropped_at IS NULL`)
    .all();

  // Map each distinctive drug term -> the trials that use it (so we search once
  // per drug and fan the results out to every trial that shares it). Keyed by
  // lowercased term so different casings across trials collapse to one search.
  const termToNct = new Map(); // lowerKey -> { term, ncts:Set }
  const nctToSponsor = new Map(); // nct_id -> sponsor (for filer matching)
  for (const t of trials) {
    nctToSponsor.set(t.nct_id, t.sponsor ?? "");
    let interventions = [];
    try {
      interventions = JSON.parse(t.interventions ?? "[]");
    } catch {
      interventions = [];
    }
    for (const term of drugTerms(interventions)) {
      const key = term.toLowerCase();
      if (!termToNct.has(key)) termToNct.set(key, { term, ncts: new Set() });
      termToNct.get(key).ncts.add(t.nct_id);
    }
  }

  console.log(`Trials: ${trials.length} | distinct drug terms: ${termToNct.size}`);
  console.log(
    anthropic
      ? `AI summaries: ON (${SUMMARY_MODEL})`
      : "AI summaries: OFF (set ANTHROPIC_API_KEY to enable) — using heuristic excerpts"
  );
  if (args.dryRun) console.log("DRY RUN — querying but not writing.\n");

  const insert = args.dryRun
    ? null
    : db.prepare(`
        INSERT INTO comms
          (nct_id, matched_term, source, cik, company, form, filed_date,
           item_codes, accession, doc_url, description, summary, created_at)
        VALUES
          (@nct_id, @matched_term, 'edgar', @cik, @company, @form, @filed_date,
           @item_codes, @accession, @doc_url, @description, @summary, @created_at)
        ON CONFLICT(nct_id, doc_url) DO UPDATE SET
          description = excluded.description,
          summary = excluded.summary,
          filed_date = excluded.filed_date
      `);

  let filingsSeen = 0;
  let linksWritten = 0;

  for (const { term, ncts } of termToNct.values()) {
    let filings = [];
    try {
      filings = await searchFilings(term, args);
    } catch (err) {
      console.warn(`  ! ${term}: ${err.message}`);
      await sleep(200);
      continue;
    }
    filingsSeen += filings.length;

    // Keep only (filing, trial) pairs where the filer is the trial's sponsor.
    const kept = []; // { f, nct }
    const perTrial = {};
    for (const f of filings) {
      if (!f.doc_url) continue;
      for (const nct of ncts) {
        if (!companyMatches(f.company, nctToSponsor.get(nct))) continue;
        if ((perTrial[nct] ?? 0) >= args.limit) continue; // cap per trial
        perTrial[nct] = (perTrial[nct] ?? 0) + 1;
        kept.push({ f, nct });
      }
    }
    console.log(
      `  ${term.padEnd(30)} ${filings.length} filings → ${kept.length} kept (same-company)`
    );

    if (insert) {
      const now = new Date().toISOString();
      for (const { f, nct } of kept) {
        const summary = await summarize(f.doc_url, f.form, term, f.company);
        insert.run({ nct_id: nct, matched_term: term, created_at: now, summary, ...f });
        linksWritten++;
      }
    }
    await sleep(150); // SEC rate-limit etiquette (<10 req/s)
  }

  db.close();

  console.log(`\nFilings fetched: ${filingsSeen} | comm-links written: ${linksWritten}`);

  if (!args.dryRun) {
    const snap = writeSnapshot();
    console.log(`Snapshot: ${snap.trials} trials, ${snap.alerts} alerts, ${snap.comms ?? "?"} comms`);
  }
}

main().catch((err) => {
  console.error("EDGAR ingestion failed:", err);
  process.exit(1);
});
